# Generated by Django 4.2.14 on 2024-07-27 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboardportalapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='end_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='student',
            name='start_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
