# Generated by Django 4.2.14 on 2024-07-28 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onboardportalapp', '0002_alter_student_end_date_alter_student_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='onboardportalapp.branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_duration',
            field=models.IntegerField(default=1),
        ),
    ]
